language: cpp
sudo: required

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - if [ `uname` = "Linux" ] && [ "$CXX" = "g++" ]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt-get update -qq;
        sudo apt-get install -qq g++-4.8;
        export CXX="g++-4.8" CC="gcc-4.8";
      fi

script: ./b DEBUG && ./b RELEASE
