language: cpp
sudo: required

matrix:
    include:
        - os: linux
          compiler: clang
        - os: linux
          compiler: gcc
          before_install:
              - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
                sudo apt-get update -qq;
                sudo apt-get install -qq g++-4.8;
                export CXX="g++-4.8" CC="gcc-4.8";
        - os: osx
          compiler: clang

script: ./b debug && ./b release
